meta_product_name: "Hymn"
meta_title: "Hymn - Play collectively without losing the fun of group blind tests!"
meta_description: "Play collectively without losing the fun of group blind tests within small or big groups, choose a Spotify playlist and here we go! Who's gonna buzz the first?"
meta_image: "Facebook_cover.jpg"
